FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir fastapi uvicorn

COPY . .

EXPOSE 8000

CMD ["uvicorn", "18_deployment.main:app", "--host", "0.0.0.0", "--port", "8000"]
